sudo: false
language: python
python:
- 3.3
- 3.4
- 3.5
script:
- pip install -U pytest
- python setup.py test --addopts='-rs'
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  # supply password with `travis encrypt --add deploy.password`
  distributions: release
